BaseURL = "https://www.shirokumo.page/"
#BaseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Shiro Kumo"
theme = "castanet"
canonifyurls = false
buildFuture = false
buildDrafts = false
dataDir = "data"
archetypedir = "archetypes"
paginate = 9

[permalinks]
	page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"
	sponsor = "/:filename"
	redirect = "/:filename"

# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "/host"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "/guests"

[[Menu.Main]]
    name = "Books"
    identifier = "books"
    url = "/books"


[params]
mainSections = ["episode"]
site_theme = "grey"
site_layout = "grid"
enable_jumbo = "false"
favicon = "img/logos/logo.png"
copyright_notice = "Copyright 2013-2020 [Shiro Kumo](https://www.shirokumo.page)"
spotify_subscribe = ""
itunes_subscribe = ""
android_subscribe = ""
google_play_subscribe = ""
stitcher_subscribe = ""
pocketcasts_subscribe = ""
mailchimp_subscribe = ""
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "Shiro Kumo is a podast exploring challenges and difficulties in the every day lives of ordinary people."
media_prefix = "https://media.blubrry.com/shirokumo/content.blubrry.com/shirokumo/"
  [params.feed]
    feed_copyright = "Copyright 2013-2020 Shiro Kumo" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "There's always clouds in the Banana Stand" #no markdown or HTML
    itunes_author = "Adhita Selvaraj" #no markdown or HTML
    itunes_summary = "A podast exploring challenges and difficulties in the every day lives of ordinary people." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Adhita Selvaraj"
    itunes_owner_email = "adhita.selvaraj@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://www.shirokumo.page/img/episode/000_trail_path.jpg" #fqdn to the image art for your podcast
    itunes_top_category = ""
    itunes_first_sub_category = ""
    itunes_second_sub_category = ""

  [params.social]
    twitter = "adhitadselvaraj"
    twitter_domain = "" # This domain shows in twitter cards as "View on `twitter_domain`"
    instagram = "adhitads"

  [params.authors]
    [params.authors.Adhita]
      name = "Adhita Selvaraj"
      thumbnail = "img/host/adhita.jpg"
      bio = "Hey there!"
      [params.authors.Adhita.social]
        twitter = "adhitadselvaraj"
