version: "3"
services:
    hugo:
        image: klakegg/hugo:0.66.0
        ports: 
          - 1313:1313
        volumes:
          - "/home/codespace/workspace/shirokumo/:/src:ro"
        environment:
          - HUGO_WATCH=true
          - HUGO_BASEURL=http://localhost/
        restart: always
